### ISSUE TITLE
Chartkick 4

### ISSUE THREAD

**Issue by ankane** [ankane/chartkick#489]
Timeline: when Chart.js 3.0 is released - `4-0-edge` branch

Plan

- [x] Make charts deferrable by default - `deferrable` branch + Chartkick.js `deferrable` branch
- [x] Better tooltips - no need to hit data point exactly
- [x] Use JavaScript's `Date.parse` for times (built-in support for ISO-8601)
- [x] Use local time for Highcharts - `{time: {useUTC: false}}` - https://github.com/ankane/react-chartkick/issues/47
- [x] Show empty (`No data`) message by default when data is empty
- [x] Show loading message when `updateData` is called (with URL or callback, make sure doesn't affect `refresh` option), with the ability to customize the loading message (https://github.com/ankane/chartkick.js/issues/119)
- [x] Add support for Chart.js 3
- [x] Remove `type` attribute from script tag ("The HTML5 specification urges authors to omit the attribute rather than provide a redundant MIME type." [source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script))
- [x] Don't rerun JavaScript for Turbolinks preview - `deferrable` branch
- [x] Add `Chartkick.destroyAll()` method - `destroyAll` branch in Chartkick.js
- [x] Change gridlines for Chart.js bar charts
- [x] Require Ruby 2.6+
- [x] If a single series data format is used for column and bar charts (not `[{name: "", data: ...}]`) and the `colors` options is passed, use it for the color of each bar
- [x] Set `nonce` automatically when present
- [x] Add `loading` option
- [x] Automatically clean up charts on Turbolinks page change - https://github.com/ankane/chartkick/issues/536#issuecomment-720229441

Maybe (non-breaking, so can wait until after release)

- [ ] More chart types - bubble, radar, polar area, combo
- [ ] Add `class` and `style` options

Probably not

- [ ] Use `data-chartkick-*` attributes to avoid inline JavaScript (more CSP friendly, possibly add option if needed to render faster)

**Comment by sent1nel** [comment]
The ability to mix chart types, for instance, line and column?

**Comment by tifafracica** [comment]
when can we make a mirror bar chart?

**Comment by chrisgeek** [comment]
> The ability to mix chart types, for instance, line and column?

This will be a cool feature really

**Comment by glaubersantana** [comment]
<%= line_chart data, messages: {empty: "No data", **loading: "wait, please..."**} %>

**Comment by josephbridgwaterrowe** [comment]
@ankane do you have any plans (in v4) of changing this library to pull in the chartkit.js package through npm or yarn rather than reproducing the code in this project?

I've been considering having a go at it, or just using the chartkit.js library in my Rails project instead... but I do like the convenience of the Rails helpers.

Are there any big issues/reasons that moving to the chartkit.js package would not be preferred?

Thanks, and great work on this library!

**Comment by archonic** [comment]
I'd like to request stacked area charts so we can create NewRelic-like charts. It would be super useful to see totals over time while breaking down the make up.

**Comment by jhubert** [comment]
@ankane Getting that edge branch in there would be great. We use Turbolinks with defer so we need to be running a patched version of chartkick to get everything working. 🎉

**Comment by steven-t-h** [comment]
@ankane would love to see animation boolean in react usage:

`<BarChart date={data} animation={true} />`

**Comment by dsounded** [comment]
Any updates on this ?
`Show loading message when updateData is called, with the ability to customize the loading message (ankane/chartkick.js#119)`

**Comment by xdmx** [comment]
Given that chartjs 3 is every day more near (beta 4 released 2 days ago), it'll be awesome if chartkick 4 will support tree shaking for it in order to only import the charts that are used and to lower as much as possible the js size by removing unused charts/logic

Are some of the things in the list above possible to be worked before the final release or would you prefer to have the final version of chartjs released? I ask because some of those things seem unrelated with chartjs itself

**Comment by ankane** [comment]
Hey all, thanks for the suggestions. 

@joshuakfarrar @chrisgeek As of now, new chart types probably won't make it into Chartkick 4 (since I think the most popular types are already covered), but may revisit in a future release.

@tifafracica You may be able to do this with the `library` option, but I haven't seen any examples with any of the charting libraries.

@glaubersantana Good call. Will either use the existing option or move all messages to top level.

@josephbridgwaterrowe Chartkick is already available on NPM. See the readme for instructions.

@archonic You can use the `stacked` option for stacked area charts.

@jhubert Check out https://github.com/ankane/chartkick/issues/536#issuecomment-720229441 for the current plan.

@steven-t-h Feel free to submit a PR to Chartkick.js (ideally for all three charting libraries).

@dsounded It's still part of the Chartkick 4 plan.

@xdmx Most of the changes are small, so just waiting for Chart.js 3 to be released. There aren't any plans to support tree shaking, but if you decide to fork and try it, feel free to share.

**Comment by ankane** [comment]
Chartkick 4 is out 🎉
